name: pixelegram
description: pixel style of telegram.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^2.2.0
  cupertino_icons: ^1.0.2
  ffi: ^1.1.2
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  global_configuration: ^2.0.0-nullsafety.1
  libtdjson: ^0.1.1
  path_provider: ^2.0.2
  permission_handler: ^8.1.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets: 
    - assets/cfg/
