name: pixelegram
description: pixel style of telegram.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^2.2.0
  country_calling_code_picker: ^2.0.0
  cupertino_icons: ^1.0.2
  dart_date: ^1.1.0
  ffi: ^1.1.2
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.8
  get_it: ^7.2.0
  global_configuration: ^2.0.0-nullsafety.1
  google_mobile_ads: ^0.13.3
  injectable: ^1.5.0
  intl: ^0.17.0
  libtdjson: ^0.1.1
  model_tdapi:
    path: model_tdapi
  path_provider: ^2.0.2
  permission_handler: ^8.1.4+2
  rxdart: ^0.27.1
  video_player: ^2.1.14

dev_dependencies:
  auto_route_generator: ^2.3.0
  build_runner: ^2.1.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.0

dependency_overrides:
  meta: 1.7.0

flutter:

  uses-material-design: true

  assets:
    - assets/cfg/
    - assets/images/

scripts: derry.yaml
